# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test

before_install:
 - sudo add-apt-repository ppa:gcovr-team/ppa -y
 - sudo apt-get -qq update
 - sudo apt-get install gcovr
 - sudo apt-get install -y libgtest-dev
 - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - sudo tar xf release-1.8.0.tar.gz
 - cd googletest-release-1.8.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - cd googletest
 - sudo cp -a include/gtest /usr/include
 - cd ../googlemock
 - sudo cp -a include/gmock /usr/include
 - sudo cp -a libgmock_main.so libgmock.so /usr/lib/
 - cd gtest
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"
 - pip install --user cpp-coveralls
 - shopt -s extglob
 - sudo ln -sf /usr/bin/gcov-5 /usr/bin/gcov

install:
 - cd ${TRAVIS_BUILD_DIR}
 # install latest LCOV (1.9 was failing for me) [1]
 - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
 - tar xf lcov_1.11.orig.tar.gz
 - sudo make -C lcov-1.11/ install
 # install lcov to coveralls conversion + upload tool
 - gem install coveralls-lcov

before_script:
 - cd ${TRAVIS_BUILD_DIR}
 - lcov --directory . --zerocounters
 - pwd
 - chmod +x autogen.sh
 - gcov -v
 - lcov -v

script:
 - cd "${TRAVIS_BUILD_DIR}"
 - lcov --zerocounters --directory .
 - lcov --capture --initial --directory . --output-file coverage.info
 - ./autogen.sh --with-unittest
 - make check
 - ls -Rla | grep gc

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --no-checksum --directory . --capture --output-file coverage.info
- lcov --remove coverage.info '*.cpp' '*.hpp' '*/test/*' '*/usr/*' -o coverage.info
- lcov --list coverage.info # debug before upload
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls

branches:
  only:
    - master

notifications:
  recipients:
    - jsiloto@cpqd.com.br
  email:
    false

